[package]
name = "olo"
version = "0.1.0"
authors = ["Tom Anderson <twic@urchin.earth.li>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
